#!/bin/bash

. /usr/share/installinux/html/scripts/common.sh

echo -n Configuring FIREWALL...

# enable forwarding
/sbin/sysctl -wq net.ipv4.ip_forward=1

# reset all firewall rules
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

# enable masquerading
/sbin/iptables -t nat -A POSTROUTING -o $WAN -j MASQUERADE

if [ "$PROXY_TRANSPARENT" == "1" ] ; then
	# all http traffic is routed through squid
	/sbin/iptables -t nat -A PREROUTING -i $LAN ! -d $LANADDRESS -p tcp --dport 80 -j DNAT --to $LANADDRESS:3128
fi
if [ "$PROXY_LOCALHOST" == "1" ] ; then
	# even the traffic generated by this machine
	/sbin/iptables -t nat -A OUTPUT -m owner --uid-owner $(id -u proxy) -j ACCEPT
	/sbin/iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to-port 3128
fi

/sbin/iptables-save > /etc/iptables/rules.v4

echo OK
